alter some new changes

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,14 +1,20 @@
 name: 01 - Building Blocks
-on: push
+on:
+  - push
+  - workflow_dispatch
 jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-      - name: Say echo-hello
+      - name: Say hello
         run: echo "Hello, World!"
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
       - name: Successful steps
         run: |
           echo "I will succeed"
